version: "3.9"

services:

  db:
    image: postgres:15-alpine
    container_name: epp_db
    environment:
      - POSTGRES_DB=epp_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 10

  epp-back:
    build: ./epp-back
    image: epp-back:latest
    container_name: epp-back
    depends_on:
      db:
        condition: service_healthy
    environment:
      - db_password=admin
      - db_user=postgres
      - db_url=jdbc:postgresql://db:5432/epp_db
      - port=8080
    ports:
      - "8080:8080"

  epp-front:
    build: ./epp-front
    image: epp-front:latest
    container_name: epp-front
    depends_on:
      - epp-back
    environment:
      - VITE_API_URL=http://localhost:8080/api/v1
    ports:
      - "4173:4173"

volumes:
  db_data:

